# Generated by Django 3.1.3 on 2022-06-29 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(help_text='Apenas números', max_length=11, verbose_name='Telefone')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Seguir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_que_seguiu', models.DateField(auto_now_add=True, verbose_name='Data que seguiu')),
                ('seguido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seguido', to='microblogging.colaborador')),
                ('seguidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seguidor', to='microblogging.colaborador')),
            ],
            options={
                'verbose_name': 'Seguir',
                'verbose_name_plural': 'Seguir',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('data_de_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microblogging.colaborador', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=200, verbose_name='Texto')),
                ('data_de_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microblogging.colaborador', verbose_name='Colaborador')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microblogging.publicacao', verbose_name='Publicação')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
